import { expect, test } from '@playwright/test'

test('loads the complete data insight dashboard without console errors', async ({ page }) => {
  const consoleErrors = []
  page.on('console', (message) => { if (message.type() === 'error') consoleErrors.push(message.text()) })
  await page.goto('')
  await expect(page.getByRole('heading', { name: '粤港一卡双号漫游数据洞察驾驶舱' })).toBeVisible()
  await expect(page.getByText('真实样本聚合', { exact: true })).toBeVisible()
  await expect(page.locator('[data-kpi="completed"]')).toContainText('31,410')
  await expect(page.locator('[data-kpi="traffic"]')).toContainText('23.7 GB')
  await expect(page.locator('[data-kpi="users"]')).toContainText('2,177')
  await expect(page.locator('[data-kpi="concentration"]')).toContainText('90.44%')
  await expect(page.getByTestId('high-value-ranking').locator('.rank-main strong').first()).toHaveText(/^1\d{2}\*{4}\d{4}$/)
  await expect(page.getByTestId('settlement-panel')).toContainText('十进制流量 × ¥5 / GB')
  await expect(page.getByTestId('settlement-panel')).toContainText('对侧收入')
  await expect(page.getByTestId('settlement-panel')).toContainText('暂不可计算')
  await expect(page.getByTestId('quality-check-list').locator('li')).toHaveCount(5)
  await expect(page.getByTestId('kpi-grid').locator('.kpi-card')).toHaveCount(6)
  await expect(page.locator('canvas')).toHaveCount(2)
  await expect(page.getByTestId('flow-map')).toBeVisible()
  expect(consoleErrors).toEqual([])
})

test('links direction filter, high-value ranking and evidence drawer', async ({ page }) => {
  await page.goto('')
  await page.getByTestId('flow-gd-hk').click()
  await expect(page.getByTestId('direction-filter')).toHaveValue('GD_TO_HK')
  await page.getByTestId('high-value-ranking').locator('.ranking-row').first().click()
  await expect(page.getByTestId('cdr-drawer')).toBeVisible()
  await expect(page.getByText('真实聚合证据')).toBeVisible()
  await expect(page.getByText('画像规则说明')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('cdr-drawer')).toBeHidden()
})

test('opens and closes centered focus details with double click', async ({ page }) => {
  const pageErrors = []
  page.on('pageerror', (error) => pageErrors.push(error.stack ?? error.message))
  await page.goto('')
  await page.getByTestId('kpi-grid').locator('.kpi-card').first().dblclick()
  await expect(page).toHaveURL(/#\/detail\/kpi-/)
  expect(pageErrors).toEqual([])
  await expect(page.getByTestId('detail-focus')).toBeVisible()
  await expect(page.getByTestId('detail-route')).toBeVisible()
  await expect(page.getByText('KPI DRILLDOWN')).toBeVisible()
  await expect(page.locator('.dashboard-shell')).toHaveClass(/is-focus-open/)
  await expect(page.locator('.focus-backdrop')).toHaveCSS('backdrop-filter', /blur\(8px\)/)
  await page.getByTestId('detail-route').dblclick()
  await expect(page).not.toHaveURL(/#\/detail\//)
  await expect(page.getByTestId('kpi-grid')).toBeVisible()

  await page.getByTestId('high-value-ranking').locator('.ranking-row').first().dblclick()
  await expect(page).toHaveURL(/#\/detail\/HV-/)
  await expect(page.getByTestId('detail-route')).toContainText('真实聚合证据')
  await expect(page.getByTestId('detail-route')).toContainText('使用规模')
  await expect(page.getByTestId('detail-route')).toContainText(/1\d{2}\*{4}\d{4}/)
  await page.getByTestId('detail-route').dblclick()
  await expect(page.getByTestId('kpi-grid')).toBeVisible()
})

test('starts, pauses and resumes guided demo mode', async ({ page }) => {
  await page.goto('')
  await page.getByTestId('tour-start').click()
  await expect(page.getByText('演示导览')).toBeVisible()
  await page.getByRole('button', { name: '暂停演示' }).click()
  await expect(page.getByRole('button', { name: '继续演示' })).toBeVisible()
  await page.getByRole('button', { name: '继续演示' }).click()
  await expect(page.getByRole('button', { name: '暂停演示' })).toBeVisible()
})
